name: Docker Image CI

on: 
  push:
    branches: []
  pull_request:
    branches:
      - main

jobs:
  build_app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

  build_images:
    name: Build Docker Images
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - image: "Database"
            needs: []
            dockerfile: Dockerfile
          - site: "Application"
            needs: 
              - build_app
            dockerfile: db/Dockerfile

    steps:
    - uses: actions/checkout@v4
    - name: Lint ${{ matrix.image }} Docker
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: ${{ matrix.dockerfile }}
